

MACRO( GLOBAL_ADD_INCLUDE COMPONENT_LOCATION )
  INSTALL_FILES( /include/${COMPONENT_LOCATION} FILES ${ARGN})
ENDMACRO( GLOBAL_ADD_INCLUDE COMPONENT_LOCATION )


MACRO( GLOBAL_ADD_SRC )
  STRING(LENGTH "${ARGN}" NOTEMPTY)
  IF(NOTEMPTY)
    SET (ENV{GLOBAL_LIBRARY_SRCS} "$ENV{GLOBAL_LIBRARY_SRCS}${ARGN};" )
  ENDIF(NOTEMPTY) 
ENDMACRO( GLOBAL_ADD_SRC )


MACRO( GLOBAL_ADD_INCLUDE_DIR )
  STRING(LENGTH "${ARGN}" NOTEMPTY)
  IF(NOTEMPTY)
    SET (ENV{GLOBAL_INCLUDE_DIRS} "$ENV{GLOBAL_INCLUDE_DIRS};${ARGN}" )
  ENDIF(NOTEMPTY) 
ENDMACRO( GLOBAL_ADD_INCLUDE_DIR )


  
