Document: orocos-bfl
Title: Debian orocos-bfl Manual
Author: <insert document author here>
Abstract: This manual describes what orocos-bfl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/orocos-bfl/orocos-bfl.sgml.gz

Format: postscript
Files: /usr/share/doc/orocos-bfl/orocos-bfl.ps.gz

Format: text
Files: /usr/share/doc/orocos-bfl/orocos-bfl.text.gz

Format: HTML
Index: /usr/share/doc/orocos-bfl/html/index.html
Files: /usr/share/doc/orocos-bfl/html/*.html

  
