Document: libbfl
Title: Debian libbfl Manual
Author: <insert document author here>
Abstract: This manual describes what libbfl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libbfl/libbfl.sgml.gz

Format: postscript
Files: /usr/share/doc/libbfl/libbfl.ps.gz

Format: text
Files: /usr/share/doc/libbfl/libbfl.text.gz

Format: HTML
Index: /usr/share/doc/libbfl/html/index.html
Files: /usr/share/doc/libbfl/html/*.html

  
